[package]
name = "salo"
version = "0.0.0"
edition = "2018"
repository = "https://github.com/semc-labs/salo"
description = "Salo: a toolset to agnostically build and deploy OS images remotely."
license = "MIT"

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
