name = "salo"
version = "0.0"

[ source ]
host = "local"

[ depends ]
idrisLibs = [ ]

[ test ]
enable = true
idrisLibs = [ "hedgehog", "sop", "pretty-show" ]
command = '''
idris2 --build test.ipkg
build/exec/runTest
'''
