#!/bin/bash

if ! [ $(id -u) = 0 ]; then
   echo "Error: Please run this script as root."
   exit 1
fi

case "$1" in
devel)
    case "$2" in
    init)
        case "$3" in
        x86_64)
            echo "-- Developing for x86_64"
            ;;
        *)
            echo $"Usage: $0 $1 $2 {x86_64}"
            exit 1
        esac
        git checkout development >> /dev/null 2>&1 && echo "--- Git checked out"
        git submodule init && echo "--- Submodules initialized"
        [ -d "build" ] && echo $"Run $0 clean to clean up your workspace before re-initializing" && exit 1
        mkdir build && echo "--- Build directory created"
        cd build && echo "--- Build directory entered"
        wget https://github.com/semissioncontrol/semcOS/releases/download/v0.0.4-alpha/semcos-$3.tar.xz
        echo "--- Extracting tarball... (this may take some time)"
        tar xfp semcos-$3.tar.xz && echo "--- Extracted successfully"
        exit 0
        ;;
    partition)
        echo "cfdisk will now be launched. Create a partition, write, and quit. Remember your partition number for $0 $1 install."
        cfdisk
        echo "Now run $0 $1 install /dev/sdXY (replacing XY with your new partition) to complete the install."
        ;;
    install)
        umount mnt && echo "-- Cleaned mnt"
        rm -rf mnt && echo "-- Removed mnt"
        mkdir mnt && echo "-- Recreated mnt"
        mount $3 mnt || echo "Mount failed: invalid partition"
        read -p "Erase all contents on $3? " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]
        then
            exit 1
        fi
        rm -rf mnt/* && echo "-- Erased $3"
        echo "Mounting to $3 - this might take a while."
        cp build/* mnt -r && echo "-- Successfully moved built files to $3"
        umount mnt && echo "-- Cleaned mnt"
        rm -rf mnt && echo "-- Removed mnt"
        ;;
    commit)
        git add $3 && echo "-- Added $3"
        echo "Creating tarball - this might take a while."
        tar cfJ semcos-tmp-build.tar.gz build/* && echo "-- Tarball created"
        git add semcos-tmp-build.tar.gz && echo "Tarball added"
        echo "Now launching git commit. The --signoff option has been enabled - please do not delete the Signed-off-by line."
        sleep 0.75
        git commit --signoff
        ;;
    *)
        echo $"Usage: $0 $1 {init|partition|install|commit}"
        exit 1
    esac
    ;;
clean)
    rm -rf *.tar.*z && echo "-- Tarballs cleaned"
    rm -rf build && echo "-- Build directory removed"
    echo "Clean exited successfully"
    exit 0
    ;;
*)
    echo $"Usage: $0 {devel|clean}"
    exit 1
esac
