#!/bin/bash

case "$1" in
devel)
    case "$2" in
    init)
        case "$3" in
        x86_64)
            echo "-- Developing for x86_64"
            ;;
        *)
            echo $"Usage: $0 $1 $2 {x86_64}"
            exit 1
        esac
        git checkout development >> /dev/null 2>&1 && echo "--- Git checked out"
        git submodule init && echo "--- Submodules initialized"
        [ -d "build" ] && echo $"Run $0 clean to clean up your workspace before re-initializing" && exit 1
        mkdir build && echo "--- Build directory created"
        cd build && echo "--- Build directory entered"
        wget https://github.com/semissioncontrol/semcOS/releases/download/v0.0.4-alpha/semcos-$3.tar.xz
        echo "--- Extracting tarball... (this may take some time)"
        tar xfp semcos-$3.tar.xz && echo "--- Extracted successfully"
        exit 0
        ;;
    install)
        umount mnt && echo "-- Cleaned mnt"
        rm -rf mnt && echo "-- Removed mnt"
        mkdir mnt && echo "-- Recreated mnt"
        mount $3 mnt || echo "Mount failed: invalid partition"
        read -p "Erase all contents on $3? " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]
        then
            exit 1
        fi
        rm -rf mnt/* && echo "-- Erased $3"
        echo "Mounting to $3 - this might take a while."
        cp build/* mnt -r && echo "-- Successfully moved built files to $3"
        umount mnt && echo "-- Cleaned mnt"
        rm -rf mnt && echo "-- Removed mnt"
        ;;
    *)
        echo $"Usage: $0 $1 {init}"
        exit 1
    esac
    ;;
clean)
    rm -rf *.tar.*z && echo "-- Tarballs cleaned"
    rm -rf build && echo "-- Build directory removed"
    echo "Clean exited successfully"
    exit 0
    ;;
*)
    echo $"Usage: $0 {devel|clean}"
    exit 1
esac
