#!/bin/sh
export SEMCOS_DESTDIR=/mnt/semcos
mkdir $SEMCOS_DESTDIR

# This section automatically creates the default directories for SEMC OS
mkdir -pv ${DESTDIR}/{bin,boot{,/grub},dev,{etc/,}opt,home,lib/{firmware,modules},lib64,mnt}
mkdir -pv ${DESTDIR}/{proc,media/{floppy,cdrom},sbin,srv,sys}
mkdir -pv ${DESTDIR}/var/{lock,log,mail,run,spool}
mkdir -pv ${DESTDIR}/var/{opt,cache,lib/{misc,locate},local}
install -dv -m 0750 ${DESTDIR}/root
install -dv -m 1777 ${DESTDIR}{/var,}/tmp
install -dv ${DESTDIR}/etc/init.d
mkdir -pv ${DESTDIR}/usr/{,local/}{bin,include,lib{,64},sbin,src}
mkdir -pv ${DESTDIR}/usr/{,local/}share/{doc,info,locale,man}
mkdir -pv ${DESTDIR}/usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -pv ${DESTDIR}/usr/{,local/}share/man/man{1,2,3,4,5,6,7,8}
for dir in ${DESTDIR}/usr{,/local}; do
    ln -sv share/{man,doc,info} ${dir}
done

# This section installs /etc/ - it needs touchups, maybe
# even use it with the package manager?
git clone https://github.com/semcos-packages/etc/
cd etc/
cp ./0.0.4a/* ${DESTDIR}/etc/
cd

# Intialize /var here

# Interesting, we'll be needing Quantum for this. I wonder how
# it'll work. I think we'll be using Quantum to install in a 
# different DESTDIR. Hopefully that works out OK. 

# Install busybox here
wget https://github.com/semcos-packages/busybox/archive/1.31.1.tar.gz
mv 1.31.1.tar.gz busybox-1.31.1.tar.gz
tar xvf busybox-1.31.1.tar.gz
cd busybox-1.31.1.tar.gz
make defconfig
# No extra config needed for now
make
make CONFIG_PREFIX=$SEMCOS_DESTDIR install

# Extra pl script we might need
cp -v examples/depmod.pl /usr/bin
chmod 755 /usr/bin/depmod.pl

cd

# Compile the kernel here
# Will this work?
wget https://github.com/semissioncontrol/semcOS/releases/download/untagged-690c9bdd0d29c5771bca/config-5.4.69
wget https://github.com/semissioncontrol/semcOS/releases/download/untagged-690c9bdd0d29c5771bca/System.map-5.4.69
wget https://github.com/semissioncontrol/semcOS/releases/download/untagged-690c9bdd0d29c5771bca/vmlinuz-5.4.69
# Hope so, if not we can compile the kernel

depmod.pl -F $SEMCOS_DESTDIR/boot/System.map-5.4.69 -b $SEMCOS_DESTDIR/lib/modules/5.4.69

# Install zlib here

# Install more things (like gcc) here

# Final touchups here
umount $SEMCOS_DESTDIR
