#!/bin/sh

# Start the network...

# PSYCH let's see if this works for now.

case "$1" in
	start)
		echo "Starting network..."
		touch /root/itworks
		;;
	stop)
		echo "Stopping network..."
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
