#!/bin/sh

# Initialize the hostname

case "$1" in
	start)
		echo "Initializing hostname...\r"
		exec 2>&1
		exec hostname -F /etc/hostname
		echo "Hostname initialized $(hostname)"
		;;
	*)
		echo $"Usage: $0 start"
		exit 1
esac

exit $?
