name: "Tests"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  builds:
    name: Run `nix run`
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix run
